FROM node:alpine
WORKDIR '/app'
COPY ./package.json .
RUN npm install

# Below can be removed as we have volume in docker-compose.yml but its better to be here for manual build.
COPY ./ ./

CMD ["npm", "run", "start"]